### PR TITLE
Use disable_sigint to allow interrupts only between iterations

### LINKED ISSUE #767: Manually stopping training SIGINT Gurobi
I think this is an issue with Gurobi, but it is worth asking here... When using Gurobi I can't stop the training procedure using SIGINT event. Although I'm able to stop the train procedure the model will not work. For example, when I try to simulate the trained model I get the following error:
Gurobi Error 10017: Unable to set attribute 'LB'

### PR DESCRIPTION
**Pull request by odow**
Closes #767

### CODE REVIEW

**Comment by odow** [comment]
@Thuener this seemed to fix things locally.

File: src/plugins/parallel_schemes.jl [hunk 1]
```diff
@@ -40,15 +40,23 @@ function master_loop(
...
+            options.post_iteration_callback(result)
+            log_iteration(options)
+            if result.has_converged
+                return result.status
+            end
+            return nothing
         end
     end
-    return
+    return return status
```
Comment (odow) [inline src/plugins/parallel_schemes.jl:59]:
```suggestion
    return status
```
