### PR TITLE
Fix support for objective_sense in deterministic_equivalent

### LINKED ISSUE #672: FEASIBILITY_SENSE returned by SDDP.deterministic_equivalent()
Hi, odow. I'm learning your package through
Documentation / Examples / (the 1st) Fast: the hydro thermal problem
```julia
function fast_hydro_thermal()
    model = SDDP.PolicyGraph(...
    ) do sp, t
        ...
    end
    det = SDDP.deterministic_equivalent(model, Gurobi.Optimizer)
    set_silent(det)
    # Notice the output here:
    println(objective_sense(det)) # FEASIBILITY_SENSE
    println(objective_function(det)) # 5 p#1 + 2.5 p#2 + 2.5 p#2
    JuMP.optimize!(det)
    println(objective_value(det)) # 10.0
    ...
    return
end

fast_hydro_thermal()
```
It seems the JuMP model `det` returned from your `SDDP.deterministic_equivalent()` function is having an objective with FEASIBILITY_SENSE.
I'm not quite clear about the meaning.

### PR DESCRIPTION
**Pull request by odow**
Closes #672

### CODE REVIEW

File: docs/src/examples/FAST_hydro_thermal.jl [hunk 1]
```diff
@@ -10,9 +10,10 @@
 using SDDP, HiGHS, Test
 
 function fast_hydro_thermal()
-    model = SDDP.PolicyGraph(
-        SDDP.LinearGraph(2),
+    model = SDDP.LinearPolicyGraph(;
+        stages = 2,
         lower_bound = 0.0,
```
Comment (odow) [inline docs/src/examples/FAST_hydro_thermal.jl:15]:
```suggestion
        upper_bound = 0.0,
```

File: test/deterministic_equivalent.jl [hunk 2]
```diff
@@ -31,7 +31,9 @@ function test_acyclic_linear()
         @stageobjective(sp, x.out)
     end
     @test SDDP.is_cyclic(model) == false
-    @test typeof(SDDP.deterministic_equivalent(model)) == JuMP.Model
+    det = SDDP.deterministic_equivalent(model)
+    @test typeof(det) == JuMP.Model
+    @test objetive_sense(det) == MOI.MIN_SENSE
```
Comment (odow) [inline test/deterministic_equivalent.jl:36]:
```suggestion
    @test objective_sense(det) == MOI.MIN_SENSE
```
